config/routes.rb
Rails.application.routes.draw do
  root to: 'public_pages#home'

  resources :albums, except: :index
  resources :faqs, except: :index
  resources :jobs, except: :index
  resources :events, except: :index
  resources :photos, only: :destroy
  resources :testemonials, except: :index
  resources :awards, except: :index
  resources :newsletters, except: :index
  devise_for :parents, only: [:sessions, :passwords]
  resources :parents, except: :index
  devise_for :admins, only: [:sessions, :passwords]
  resources :admins, except: :index

  # Administration routes
  get 'admin' => 'admin_pages#dashboard', as: :admin_dashboard
  get 'admin/awards' => 'awards#index'
  get 'admin/faqs' => 'faqs#index'
  get 'admin/albums' => 'albums#index'
  get 'admin/events' => 'events#index'
  get 'admin/jobs' => 'jobs#index'
  get 'admin/newsletters' => 'newsletters#index'
  get 'admin/parents' => 'parents#index'
  get 'admin/testemonials' => 'testemonials#index'
  get 'admin/admins' => 'admins#index'

  # Public routes
  get 'about-us' => 'public_pages#about_us'
  get 'nursery' => 'public_pages#nursery'
  get 'staff' => 'public_pages#staff'
  get 'contact' => 'public_pages#contact'
  post 'contact' => 'public_pages#contact'
  get 'newsletters' => 'public_pages#newsletters'
  get 'careers' => 'public_pages#careers'
  get 'testimonials' => 'public_pages#testimonials'
  get 'education_fund' => 'public_pages#education_fund'
  get 'eyfs_curriculum' => 'public_pages#eyfs_curriculum'
  get 'british_values' => 'public_pages#british_values'
  get 'save_money' => 'public_pages#save_money'
  get 'faqs' => 'public_pages#faqs'
  post 'request_viewing' => 'public_pages#request_viewing'
  get 'download_fees_terms_and_conditions' => 'public_pages#fees_terms_and_conditions'

  #Parents only
  get 'gallery' => 'public_pages#gallery'
  get 'news' => 'public_pages#news'
  get 'album/:id' => 'public_pages#album', as: 'parents_album'
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_validation :set_password
  after_create :send_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :recoverable,
              :rememberable, :trackable, :validatable

  validates_presence_of :username

  private

  def set_password
    password = SecureRandom.urlsafe_base64(6)
    self.password = password unless self.superadmin
    self.generated_password = self.password
  end

  def send_email
    AdminMailer.send_admin_password(self).deliver
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos, as: :imageable, dependent: :destroy
  validates_presence_of :name
  default_scope -> { order(created_at: :desc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, dependent: :destroy
  validates_attachment_content_type :photo, content_type: ["image/jpeg", "image/gif", "image/png"]
  validates_presence_of :title

  default_scope -> { order(created_at: :desc) }
end

app/models/break.rb
class Break < ApplicationRecord
  validates_presence_of :description, :start_date, :end_date
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :description, :start_date, :end_date
end

app/models/faq.rb
class Faq < ApplicationRecord
  validates_presence_of :question, :answer
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :title, :description
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  validates_presence_of :name
  has_attached_file :document, use_timestamp: false, dependent: :destroy
  validates_attachment :document,
                                      content_type: { content_type: "application/pdf" },
                                      presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/parent.rb
class Parent < ApplicationRecord
  before_validation :set_password
  after_create :send_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :trackable, :validatable

  validates :title, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  private

  def set_password
    password = SecureRandom.urlsafe_base64(6)
    self.password = password
    self.generated_password = password
  end

  def send_email
    AdminMailer.send_parent_password(self).deliver
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :imageable, polymorphic: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },
                                            default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /image\/.*\z/
end

app/models/testemonial.rb
class Testemonial < ApplicationRecord
  has_one :photo, as: :imageable, dependent: :destroy
  # accepts_nested_attributes_for :photo

  validates_presence_of :description, :name

  default_scope -> { order(created_at: :desc) }
end

app/helpers/admins_helper.rb
module AdminsHelper
  def get_title object
    title = case
    when object.class == Faq then object.question
    when object.class == Event then event_text(object)
    when object.class == Newsletter then object.name
    when object.class == Parent then parent_full_name object
    when object.class == Admin then object.username
    else
      object.title
    end
  end

  def event_text event
    start = event.start_date
    finish = event.end_date
    start == finish ? "Day off on #{start.strftime("%e %B")}" :
                                "From #{start.strftime('%e %B').strip} to #{finish.strftime('%e %B %Y').strip}"
  end

  def parent_full_name parent
    "#{parent.title} #{parent.first_name} #{parent.last_name}"
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admins/_form.html.erb
<%= simple_form_for(admin) do |f| %>

  <%= f.input :username %>
  <%= f.input :email %>
  <p>
    <strong>Note:</strong> Password will be automatically created and send to the admin's email.
  </p>
  <% if current_admin.superadmin && !admin.new_record? %>
    <%= f.input :password %>
  <% end %>
  <%= f.button :submit %>

<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

app/views/admins/index.html.erb
<%= render partial: 'shared/index', locals: {objects: @admins} %>

app/views/admins/new.html.erb
<h1 class="text-center">New Admin</h1>

<%= render 'form', admin: @admin %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.generated_password %>
</p>

<p class="text-right">
  <%= link_to fa_icon("pencil 2x", id: "pencil"), edit_admin_path(@admin),
                                                                          title: "Edit" %>
  <%= link_to fa_icon("trash 2x", id: "bin"), @admin,
                                                                     method: :delete,
                                                                     data: { confirm: "Are you sure?" },
                                                                     title: "Delete" %>
</p>

app/views/shared/_blueimp_gallery.html.erb
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_index.html.erb
<div id="index-page">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 text-center" id="admin-controls">
      <h1>
        <%= link_to fa_icon("plus 2x", id: "plus"),
                            eval("new_#{params[:controller].chomp('s').underscore}_path") %>
      </h1>
      <h3>
        <%= link_to "New #{params[:controller].chomp('s').capitalize}",
                              eval("new_#{params[:controller].chomp('s').underscore}_path") %>
      </h3>
    </div>
  </div>
  <div class="row">
  <% objects.each do |object| %>
    <div class="col-xs-12 col-sm-8">
      <h3><%= link_to get_title(object), object %></h3>
    </div>
    <div class="col-xs-12 col-sm-4 text-right resource-controls">
      <%= link_to fa_icon("pencil 2x", id: "pencil"), send("edit_#{object.class.to_s.underscore}_path", object), title: "Edit" %>
      <%= link_to fa_icon("trash 2x", id: "bin"), object, method: :delete, data: { confirm: "Are you sure?" }, title: "Delete" %>
    </div>
  <% end %>
  </div>
</div>